services:
  postgres:
    image: postgres:15
    container_name: smartshop-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smartshopdb
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: smartshop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@smartshop.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build: .
    container_name: smartshop-app
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  pgdata: